# Generated by Django 2.2.7 on 2019-11-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('objetivo', models.CharField(max_length=300)),
                ('fecha_ini', models.DateField()),
                ('fecha_limite', models.DateField()),
                ('estado', models.CharField(max_length=20)),
                ('fase', models.CharField(choices=[('ANA', 'Analisis'), ('DIS', 'Diseño'), ('COD', 'Codificacion'), ('PRU', 'Prueba'), ('MAN', 'Mantenimiento')], default='ANA', max_length=15)),
            ],
        ),
    ]
