# Generated by Django 2.2.6 on 2019-12-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_auto_20191215_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='cant_dias_atrasados',
            field=models.IntegerField(default=0),
        ),
    ]
