# Generated by Django 2.2.6 on 2019-12-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linea_base',
            name='estado',
            field=models.CharField(choices=[('HAB', 'Habilitada'), ('BLO', 'Bloqueada'), ('FIN', 'Finalizado')], default='HAB', max_length=15),
        ),
    ]
